### ISSUE TITLE
Query Regarding Usage Limitations and Payment

### ISSUE THREAD

**Issue by clsteam** [Hugo-Persson/obsidian-ocrlatex#1]
Dear @Hugo-Persson ,

I wanted to extend my heartfelt gratitude for your remarkable work on the [obsidian-ocrlatex](https://github.com/Hugo-Persson/obsidian-ocrlatex). This incredible plugin has significantly addressed the challenges I faced in managing mathematical formulas within my notes, vastly boosting my productivity. The seamless integration of the obsidian-ocrlatex plugin into my workflow has been a game-changer, simplifying the process of dealing with mathematical equations within my notes in a way that has truly transformed my note-taking experience.

Your dedication and expertise in crafting such a powerful tool have not only enhanced my personal efficiency but undoubtedly have the potential to assist countless others facing similar obstacles in their note-taking endeavors. Your commitment to developing this plugin is genuinely commendable, and I am deeply grateful for the effort and skill you've invested in its creation.

On another note, I have a query regarding the usage limitations of the [Plugin Name]. As per the current information available on the website (https://simpletex.cn/), it appears that the service offers a limit of 1000 free API calls. Once these free API calls are exhausted, will there be a need to purchase additional usage? I understand that the website is currently in its public testing phase, and the specifics of payment standards haven't been provided yet.

Thank you for your invaluable contribution to the community, and I sincerely hope that this exceptional plugin continues to reach and benefit many more individuals, making their tasks easier and more enjoyable.

Warm regards,
clsteam

**Comment by Hugo-Persson** [comment]
Thank you so much @clsteam!

If there are any improvements, you want don't hesitate to raise an issue. 

I believe you have 1000 calls per month. If you go to the API dashboard and then resource packs. You will see a button on the bottom of the page where you can redeem 1000 calls each month (see image below). I don't know if this is always going to be an option. If the service stop being free, I will look into self-hosted alternatives like https://github.com/lukas-blecher/LaTeX-OCR.

<img width="574" alt="image" src="https://github.com/Hugo-Persson/obsidian-ocrlatex/assets/47189713/69e653d3-163d-4b80-a760-422c6b06919d">

**Comment by clsteam** [comment]
I wanted to extend my sincere thanks for your prompt response. Your dedication to engaging with users is truly commendable. I remain immensely grateful for your efforts in developing such an outstanding plugin. Its functionality has significantly enhanced my workflow and productivity.

I truly believe that this plugin has the potential to benefit many others in the community. Hence, I am eager to share it with my friends and colleagues who, I am certain, will find it equally valuable.

Once again, thank you for your exceptional work, and I look forward to witnessing this plugin gaining the attention and recognition it deserves.

Thank you once again for your support and the exceptional plugin you've developed!
Warm regards,
clsteam

**Comment by Hugo-Persson** [comment]
Thank you so much!

Please share and share the project. 👏
