### ISSUE TITLE
I apologize, I'm getting an error deploying texify to the server.

### ISSUE THREAD

**Issue by math-feng** [Hugo-Persson/obsidian-ocrlatex#12]
How exactly this error came about is not clear to me. Because I don't know the server very well. The first item about texify I put in the public ip address, followed by the account and password, which is the account and password I use to log into the cloud server.

One weird thing, I obviously changed the first item, but it still comes up every time I report an error.

![image](https://github.com/Hugo-Persson/obsidian-ocrlatex/assets/78469397/e69ff62b-c7fb-4f93-8377-3a458ebe4d78)

**Comment by Hugo-Persson** [comment]
Hi! Is this the same issue as https://github.com/Hugo-Persson/obsidian-ocrlatex/issues/13? 

Could you send a screenshot of your configured settings?

**Comment by math-feng** [comment]
yes

I'm omitting three numbers on the first line for the sake of privacy

**Comment by math-feng** [comment]
A very important fact is that no matter how I set it up, the server address at runtime points to the local

**Comment by Hugo-Persson** [comment]
Ok nice catch! I will look into it before the day is done and get back to you.

**Comment by Hugo-Persson** [comment]
I have released a new version `1.1.1` could you try that @math-feng ?

**Comment by Hugo-Persson** [comment]
Nvm use version `1.1.2`, fixed another bug

**Comment by math-feng** [comment]
```
root@iZkzr13nj40jdwZ:~# curl -X POST -F "image=@/www/wwwroot/resource/Obsidian_24_04_05_138.png" http://127.0.0.1:8000/predict
{"error":"We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like vikp/texify is not the path to a directory containing a file named config.json.\nCheckout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'."}
root@iZkzr13nj40jdwZ:~# 
```
This is the result of my testing on the server, probably caused by my network limitations in China.

**Comment by Hugo-Persson** [comment]
Oh yeah that might be a problem with China. Maybe use a VPN?

**Comment by math-feng** [comment]
If you use a VPN in a server, the server will be blocked

**Comment by Hugo-Persson** [comment]
I am closing this issue and will continue in https://github.com/Hugo-Persson/texify-wep-api/issues/1
