### ISSUE TITLE
Screenshot quickly

### ISSUE THREAD

**Issue by math-feng** [Hugo-Persson/obsidian-ocrlatex#2]
May I ask how you take quick screenshots in Obsidian? Is it possible to come up with an action for the plugin to take a quick screenshot of an image? Because I'm using the screenshot function that comes with Windows, and every time I take a screenshot a prompt box pops up in the bottom right corner, which is distracting. Anyway, thank you very much for your efforts!

**Comment by Hugo-Persson** [comment]
Hmm, I use Shottr on Mac and built in screenshot tool on Windows. I would say it is better to try another screenshot tool, such as https://getsharex.com/

**Comment by math-feng** [comment]
This tool screenshot experience is fantastic, thanks a lot! @Hugo-Persson
